### ISSUE TITLE
Initial run is failing

### ISSUE THREAD

**Issue by emingenc** [logan-connolly/mychef#57]
Documentation needed for frontend build or another make command will be usefull

```bash
cd frontend 
yarn install
nuxt generate
```

Another things backend failing unless you build images locally since `backend/api/start.sh` needed to run 

it gives this error

```
 File "/opt/mychef/app/main.py", line 4, in <module>
    from app.api.v1.router import router
  File "/opt/mychef/app/api/v1/router.py", line 3, in <module>
    from .endpoints import ingredients, recipes, sources
  File "/opt/mychef/app/api/v1/endpoints/ingredients.py", line 12, in <module>
    from app.db.repositories.ingredients import IngredientsRepository
ModuleNotFoundError: No module named 'app.db.repositories'
[2022-03-23 19:13:18 +0000] [12] [INFO] Worker exiting (pid: 12)
[2022-03-23 19:13:18 +0000] [1] [INFO] Shutting down: Master
[2022-03-23 19:13:18 +0000] [1] [INFO] Reason: Worker failed to boot.```

**Comment by logan-connolly** [comment]
@emingenc thanks for the feedback!

> Documentation needed for frontend build or another make command will be usefull

Does the make command `make assets` solve the problem? I basically have that command for running the install, build and generate (static). I also always use yarn commands to run the nuxt specific commands. 

> Another things backend failing unless you build images locally since backend/api/start.sh needed to run

Are you trying to run it via docker-compose? or locally in an virtual environment?

**Comment by logan-connolly** [comment]
@emingenc great find here:

> ModuleNotFoundError: No module named 'app.db.repositories'

Was a refactoring bug - forgot to rename imports after renaming the modules (e648bd7f4a96db08409de6fc61b76b61ebd1fcb5). Really appreciate the find! Could you confirm that it runs now?

**Comment by emingenc** [comment]
Thank you. I just followed again readme and everything worked fine. I just missed `make assets` command when i tried first time. About other error did not occur again. 
Nice project I really liked it. I came to inspect and get inspired some good practice.

**Comment by logan-connolly** [comment]
@emingenc really appreciate the kind words!
