### ISSUE TITLE
Scraping issue: When scraper interrupted and restarted again it cant continue since CloseSpider("Recipe already exists")

### ISSUE THREAD

**Issue by emingenc** [logan-connolly/mychef#59]
<img width="728" alt="Screen Shot 2022-03-31 at 11 26 02 PM" src="https://user-images.githubusercontent.com/81563574/161143404-72fe0b13-29a3-4a11-bd0c-df47d6427a26.png">

When I comment that line it worked fine and backend updated. before that i tried like couple times and every time scraper failed Recipe already exist.
I guess in my first run scraper interrupted and when I restart `make scrape` it fails on same recipe and this does not allow to update further recipes with backend

**Comment by logan-connolly** [comment]
Related to #58
